-- Transport/audit state only. This table is intentionally separate from authoritative academic tables.
create table if not exists public.bot_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  source text not null default 'whatsapp',
  phone text not null,
  intent text not null,
  payload jsonb not null default '{}'::jsonb,
  response jsonb,
  created_at timestamptz not null default now()
);

create index if not exists bot_events_phone_created_idx
  on public.bot_events (phone, created_at desc);

create index if not exists bot_events_intent_created_idx
  on public.bot_events (intent, created_at desc);

alter table public.bot_events enable row level security;

-- No public client policy is granted here. Server-side service-role access is expected.
