const crypto=require('crypto');
const {db}=require('./knowledge');

const USER_AGENT='NOUN-Student-Bot-Intelligence/1.0 (+https://nou.edu.ng/)';
const MAX_BYTES=5*1024*1024;

function sha256(s){return crypto.createHash('sha256').update(s).digest('hex')}
function stripHtml(html){return String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\s+/g,' ').trim()}
function titleOf(html){const m=String(html||'').match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?stripHtml(m[1]).slice(0,500):null}
function canonicalOf(html,fallback){const m=String(html||'').match(/<link[^>]+rel=["'][^"']*canonical[^"']*["'][^>]+href=["']([^"']+)["']/i)||String(html||'').match(/<link[^>]+href=["']([^"']+)["'][^>]+rel=["'][^"']*canonical[^"']*["']/i);return m?m[1]:fallback}
function extractLinks(html,base){const out=[];const re=/<a[^>]+href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<500){try{const url=new URL(m[1],base).href;if(/^https?:/i.test(url))out.push({url,title:stripHtml(m[2]).slice(0,300)})}catch{}}return out}
function normalize(html){const text=stripHtml(html);return text.slice(0,1500000)}
function confidence(source){if(source.authority_tier===1)return .97;if(source.authority_tier===2)return .94;if(source.authority_tier===3)return .9;return .7}
function validate(source,httpStatus,content){const official=/^https:\/\/(?:www\.)?(?:nou\.edu\.ng|dqa\.nou\.edu\.ng|dea\.nou\.edu\.ng)\//i.test(source.url);const newsOfficial=/^https:\/\/nounnews\.nou\.edu\.ng\//i.test(source.url);const ok=(httpStatus>=200&&httpStatus<300)&&content.length>80&&(official||newsOfficial||source.authority_tier>=4);return {ok,confidence:Math.min(confidence(source),ok?.99:.25),reason:ok?'source reachable, content present, authority policy satisfied':'source failed reachability/content/authority validation'}}

async function fetchSource(source){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(source.url,{headers:{'user-agent':USER_AGENT,'accept':'text/html,application/xhtml+xml,application/pdf;q=0.9,*/*;q=0.8'},signal:controller.signal,redirect:'follow'});const buf=Buffer.from(await r.arrayBuffer());if(buf.length>MAX_BYTES)throw new Error('source exceeds 5MB monitor limit');const contentType=r.headers.get('content-type')||'';const raw=buf.toString('utf8');const content=contentType.includes('html')?normalize(raw):raw.slice(0,1500000);return {status:r.status,contentType,content,raw,title:contentType.includes('html')?titleOf(raw):null,canonicalUrl:contentType.includes('html')?canonicalOf(raw,r.url):r.url,links:contentType.includes('html')?extractLinks(raw,r.url):[]};}finally{clearTimeout(timeout)}}

async function monitorOne(source){const fetched=await fetchSource(source);const hash=sha256(`${source.url}\n${fetched.content}`);const validation=validate(source,fetched.status,fetched.content);const {data:previous}=await db.from('intelligence_snapshots').select('id,content_hash,fetched_at').eq('source_id',source.id).order('fetched_at',{ascending:false}).limit(1).maybeSingle();
const {data:snapshot,error:snapErr}=await db.from('intelligence_snapshots').insert({source_id:source.id,fetched_at:new Date().toISOString(),http_status:fetched.status,content_hash:hash,title:fetched.title,content_text:fetched.content,canonical_url:fetched.canonicalUrl,parse_status:validation.ok?'parsed':'failed',metadata:{content_type:fetched.contentType,links:fetched.links.slice(0,100)}}).select('id').single();
if(snapErr && snapErr.code==='23505'){await db.from('intelligence_sources').update({last_checked_at:new Date().toISOString(),last_success_at:validation.ok?new Date().toISOString():undefined,last_hash:hash,last_status:validation.ok?'unchanged':'failed',failure_count:validation.ok?0:source.failure_count+1,updated_at:new Date().toISOString()}).eq('id',source.id);return {changed:false,validated:validation.ok,error:null}}
if(snapErr)throw snapErr;
const changed=!previous||previous.content_hash!==hash;
let change=null;if(changed){const {data:c,error:ce}=await db.from('intelligence_changes').insert({source_id:source.id,previous_snapshot_id:previous?.id||null,current_snapshot_id:snapshot.id,change_type:previous?'content_changed':'initial_snapshot',summary:previous?'Source content changed; downstream parser/AI review required.':'Initial source snapshot captured.',authority_tier:source.authority_tier,confidence:validation.confidence,validation_status:validation.ok?'validated':'rejected',abba_status:validation.ok?'eligible':'rejected',metadata:{source_type:source.source_type,title:fetched.title,canonical_url:fetched.canonicalUrl}}).select('id').single();if(ce)throw ce;change=c}
await db.from('intelligence_sources').update({last_checked_at:new Date().toISOString(),last_success_at:validation.ok?new Date().toISOString():source.last_success_at,last_hash:hash,last_status:validation.ok?(changed?'changed':'unchanged'):'failed',failure_count:validation.ok?0:(source.failure_count||0)+1,updated_at:new Date().toISOString()}).eq('id',source.id);
return {changed,validated:validation.ok,change_id:change?.id||null,title:fetched.title,status:fetched.status};}

async function runMonitor(){const started=Date.now();const {data:run,error:re}=await db.from('intelligence_runs').insert({status:'running'}).select('id').single();if(re)throw re;const {data:sources,error:se}=await db.from('intelligence_sources').select('*').eq('enabled',true);if(se)throw se;let success=0,changes=0,errors=0,validated=0;const results=[];for(const source of sources||[]){try{const due=!source.last_checked_at||(Date.now()-new Date(source.last_checked_at).getTime()>=source.poll_interval_minutes*60000);if(!due){results.push({source_key:source.source_key,skipped:true});continue}const r=await monitorOne(source);success++;if(r.changed)changes++;if(r.validated)validated++;results.push({source_key:source.source_key,...r});}catch(e){errors++;results.push({source_key:source.source_key,error:String(e.message||e)});await db.from('intelligence_sources').update({last_checked_at:new Date().toISOString(),last_status:'failed',failure_count:(source.failure_count||0)+1,updated_at:new Date().toISOString()}).eq('id',source.id)}}const status=errors&&success===0?'failed':'completed';await db.from('intelligence_runs').update({finished_at:new Date().toISOString(),source_count:(sources||[]).length,success_count:success,change_count:changes,validation_count:validated,error_count:errors,status,metadata:{duration_ms:Date.now()-started,results}}).eq('id',run.id);return {run_id:run.id,status,source_count:(sources||[]).length,success_count:success,change_count:changes,validation_count:validated,error_count:errors,results}}

module.exports={runMonitor};
