const https = require('node:https');
const OFFICIAL_NOUN={base:'https://nou.edu.ng',authority_tier:1,source_type:'official_noun'};
function clean(value,max=12000){return String(value||'').trim().slice(0,max)}
function normalizeSource(raw={},adapter=OFFICIAL_NOUN){return{title:clean(raw.title,240),url:clean(raw.url,500),authority_tier:Number(adapter.authority_tier||4),source_type:clean(adapter.source_type||'external',80),retrieved_at:new Date().toISOString(),verified_at:raw.verified_at||null,content:clean(raw.content),metadata:raw.metadata||{}}}
function buildEvidence(rows=[]){return rows.filter(x=>clean(x.content)).map(x=>normalizeSource(x,x))}
function isAllowedUrl(value){try{const u=new URL(value);if(u.protocol!=='https:')return false;const h=u.hostname.toLowerCase();if(['localhost','0.0.0.0'].includes(h)||/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2\d|3[0-1])\./.test(h))return false;const allowed=String(process.env.NOUN_ALLOWED_SOURCE_DOMAINS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);return !allowed.length||allowed.some(domain=>h===domain||h.endsWith(`.${domain}`))}catch{return false}}
function fetchText(url,timeoutMs=6000,maxBytes=180000){if(!isAllowedUrl(url))return Promise.reject(new Error('source host not allowed'));return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'user-agent':'NOUN-BOT/2.1 source retrieval',accept:'text/html,text/plain;q=0.9,*/*;q=0.1'}},res=>{const status=res.statusCode||500;if(status<200||status>=300){res.resume();return reject(new Error(`HTTP ${status}`))}let body='';res.setEncoding('utf8');res.on('data',chunk=>{body+=chunk;if(Buffer.byteLength(body,'utf8')>maxBytes)req.destroy(new Error('source too large'))});res.on('end',()=>resolve(body.slice(0,maxBytes)))});req.setTimeout(timeoutMs,()=>req.destroy(new Error('source timeout')));req.on('error',reject)})}
function extractText(html){return clean(String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' '),12000)}
function queryTerms(query){return[...new Set(String(query||'').toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2))].slice(0,8)}
function relevance(query,content){const terms=queryTerms(query);const haystack=String(content||'').toLowerCase();return terms.length?terms.reduce((score,term)=>score+(haystack.includes(term)?1:0),0)/terms.length:0}
async function fetchSource(raw){const url=String(raw.url||raw.source_url||'').trim();if(!isAllowedUrl(url))throw new Error('source url not allowed');const content=extractText(await fetchText(url));return normalizeSource({title:raw.title||raw.name||url,url,content,verified_at:raw.verified_at||null,metadata:raw.metadata||{}},{authority_tier:Number(raw.authority_tier||raw.source_tier||4),source_type:raw.source_type||'registered_source'})}
async function fetchLiveSources(query,options={}){const q=clean(query,240);if(!q)return{facts:[],sources:[],confidence:'low'};const registered=(options.sources||[]).filter(x=>x&&(x.source_url||x.url)).slice(0,6);const envUrls=String(process.env.NOUN_SOURCE_URLS||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,6).map(url=>({url,authority_tier:4,source_type:'configured_external'}));const defaults=(options.paths&&options.paths.length?options.paths.slice(0,6):['/calendar/','/faqs/','/e-courseware/','/news/','/']).map(path=>({url:new URL(path,OFFICIAL_NOUN.base).toString(),authority_tier:1,source_type:'official_noun',title:`NOUN ${path.replace(/\/+$/,'').split('/').filter(Boolean).join(' ')||'home'}`}));const jobs=[...registered,...envUrls,...defaults].slice(0,12).map(fetchSource);const settled=await Promise.allSettled(jobs);const found=settled.filter(x=>x.status==='fulfilled').map(x=>x.value).map(x=>({...x,relevance:relevance(q,x.content)})).filter(x=>x.relevance>0).sort((a,b)=>((b.authority_tier||4)-(a.authority_tier||4))||((b.relevance||0)-(a.relevance||0))).slice(0,options.limit||5).map(({relevance:_relevance,...x})=>x);return{facts:found,sources:found.map(x=>({tier:x.authority_tier,title:x.title,url:x.url,kind:'live',source_type:x.source_type})),confidence:found.length?'high':'low'}}
module.exports={normalizeSource,buildEvidence,fetchLiveSources,isAllowedUrl};
