const crypto = require('crypto');
const { createClient } = require('@supabase/supabase-js');

const db = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth:{persistSession:false} });
const PARSER_VERSION='noun-sync-v1';
const SOURCES=[
 {key:'programmes',url:'https://retridol.nou.edu.ng/programmes/',type:'programme_catalogue',title:'NOUN Programmes — List of Faculties, Departments and Programmes'},
 {key:'ecourseware',url:'https://nou.edu.ng/e-courseware/',type:'courseware_index',title:'NOUN e-Courseware'},
 {key:'agric',url:'https://nou.edu.ng/ecourseware-faculty-of-agric/',type:'courseware_faculty',title:'eCourseware Faculty of Agricultural Sciences'},
 {key:'arts',url:'https://nou.edu.ng/ecourseware-faculty-of-arts/',type:'courseware_faculty',title:'eCourseware Faculty of Arts'},
 {key:'edu',url:'https://nou.edu.ng/ecourseware-faculty-of-edu/',type:'courseware_faculty',title:'eCourseware Faculty of Education'},
 {key:'health',url:'https://nou.edu.ng/ecourseware-faculty-of-health-sc/',type:'courseware_faculty',title:'eCourseware Faculty of Health Sciences'},
 {key:'law',url:'https://nou.edu.ng/ecourseware-faculty-of-law/',type:'courseware_faculty',title:'eCourseware Faculty of Law'},
 {key:'management',url:'https://nou.edu.ng/ecourseware-faculty-of-management-sc/',type:'courseware_faculty',title:'eCourseware Faculty of Management Sciences'},
 {key:'sciences',url:'https://nou.edu.ng/ecourseware-faculty-of-sciences/',type:'courseware_faculty',title:'eCourseware Faculty of Sciences'},
 {key:'social',url:'https://nou.edu.ng/ecourseware-faculty-of-social-sc/',type:'courseware_faculty',title:'eCourseware Faculty of Social Sciences'},
 {key:'computing',url:'https://nou.edu.ng/ecourseware-faculty-of-computing-2/',type:'courseware_faculty',title:'eCourseware Faculty of Computing'},
 {key:'degs',url:'https://nou.edu.ng/ecourseware-degs/',type:'courseware_degs',title:'eCourseware DE & General Studies'},
 {key:'policies',url:'https://dqa.nou.edu.ng/policies/',type:'policy_index',title:'NOUN Directorate of Quality Assurance Policies'}
];
function clean(s){return String(s||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim()}
function cells(row){return [...row.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(m=>clean(m[1]))}
function tables(html){return [...html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(m=>cells(m[1])).filter(r=>r.length)}
function hash(s){return crypto.createHash('sha256').update(s).digest('hex')}
function award(programme){const p=programme.toUpperCase(); if(p.includes('PHD')) return p.includes('MPHIL')?'MPhil/PhD':'PhD'; if(p.includes('MPHIL')) return 'MPhil'; if(p.includes('PGD')) return 'PGD'; if(p.includes('M.A')||p.includes('M.ED')||p.includes('M.SC')||p.includes('MSC')||p.includes('MASTER')) return 'Masters'; if(p.includes('B.')||p.includes('BSC')||p.includes('BA ')||p.includes('B.A')) return 'Undergraduate'; if(p.includes('DIPLOMA')) return 'Diploma'; if(p.includes('CERT')) return 'Certificate'; return 'Other'}
async function fetchSource(source){const started=Date.now(); const r=await fetch(source.url,{headers:{'user-agent':'NOUN-Student-Bot-Knowledge-Sync/1.0'}}); const html=await r.text(); return {html,status:r.status,hash:hash(html),ms:Date.now()-started}}
async function sourceRecord(source,fetchResult){const {data:existing}=await db.from('knowledge_sources').select('id').eq('source_url',source.url).maybeSingle(); const payload={source_url:source.url,source_type:source.type,authority_tier:1,title:source.title,publisher:'National Open University of Nigeria',retrieved_at:new Date().toISOString(),content_hash:fetchResult.hash,status:fetchResult.status===200?'active':'failed',notes:`Parser ${PARSER_VERSION}; HTTP ${fetchResult.status}`}; if(existing){await db.from('knowledge_sources').update(payload).eq('id',existing.id);return existing.id} const {data,error}=await db.from('knowledge_sources').insert(payload).select('id').single(); if(error)throw error; return data.id}
async function syncProgrammes(html,url){const rows=tables(html); const body=rows.filter(r=>r.length>=3 && /faculty/i.test(r[0])===false && /department/i.test(r[1])===false); let seen=0,inserted=0,rejected=0; for(const r of body){const faculty=clean(r[1]||r[0]),department=clean(r[2]),programme=clean(r[3]||r[2]); if(!faculty||!department||!programme||/^null$/i.test(programme)) {rejected++;continue} seen++; let f=await db.from('academic_faculties').upsert({name:faculty,source_url:url,source_tier:1,verified_at:new Date().toISOString(),active:true},{onConflict:'name'}).select('id').single(); if(f.error)throw f.error; let d=await db.from('academic_departments').upsert({faculty_id:f.data.id,name:department,source_url:url,source_tier:1,verified_at:new Date().toISOString(),active:true},{onConflict:'faculty_id,name'}).select('id').single(); if(d.error)throw d.error; const p={department_id:d.data.id,title:programme,award_type:award(programme),programme_level:award(programme),source_url:url,source_tier:1,verification_status:'verified',verified_at:new Date().toISOString(),active:true}; const q=await db.from('programmes').upsert(p,{onConflict:'title,department_id'}).select('id').single(); if(q.error)throw q.error; inserted++ } return {seen,inserted,rejected}}
async function syncCourseware(html,url,title){const rows=tables(html); let seen=0,upserted=0,rejected=0; const faculty=title.replace(/^eCourseware Faculty of /i,'').replace(/^eCourseware /i,'').trim(); for(const r of rows){if(r.length<3)continue; const code=clean(r[0]).replace(/\s+/g,'').toUpperCase(); const courseTitle=clean(r[1]); if(!/^[A-Z]{2,6}\d{3,4}$/.test(code)||!courseTitle)continue; const credit=Number(clean(r[2]).replace(/[^0-9.]/g,'')); const level=clean(r[3]); const semester=Number(clean(r[4]).replace(/[^0-9]/g,''))||null; seen++; const c=await db.from('courses').upsert({course_code:code,title:courseTitle,credit_units:Number.isFinite(credit)&&credit>0?credit:null,source_url:url,source_tier:1,verification_status:'verified',verified_at:new Date().toISOString(),active:true},{onConflict:'course_code'}).select('id').single(); if(c.error){rejected++;continue} const f=await db.from('academic_faculties').upsert({name:faculty,source_url:url,source_tier:1,verified_at:new Date().toISOString(),active:true},{onConflict:'name'}).select('id').single(); if(f.error){rejected++;continue} const o=await db.from('course_offerings').upsert({course_id:c.data.id,faculty_id:f.data.id,level:level||null,semester,credit_units:Number.isFinite(credit)&&credit>0?credit:null,source_url:url,source_tier:1,verified_at:new Date().toISOString()},{onConflict:'course_id,faculty_id,level,semester'}); if(o.error)rejected++; else upserted++ } return {seen,inserted:upserted,rejected}}
async function syncPolicyIndex(html,url){const rows=tables(html);let seen=0;for(const r of rows){if(r.length<2)continue;const code=r.find(x=>/^NQSA\/POL\//i.test(x));const title=r.find(x=>/policy/i.test(x)&&x!==code);if(!title)continue;seen++;await db.from('noun_policies').upsert({policy_code:code||null,title,source_url:`${url}#${encodeURIComponent(title)}`,policy_area:null,authority_tier:1,retrieved_at:new Date().toISOString(),status:'active',summary:null},{onConflict:'source_url'}).then(()=>{});}return {seen,inserted:seen,rejected:0}}
async function run(key){const source=SOURCES.find(s=>s.key===key);if(!source)throw new Error(`Unknown source: ${key}`);const run=await db.from('sync_runs').insert({sync_type:source.type,source_url:source.url,status:'started'}).select('id').single();const runId=run.data.id;try{const f=await fetchSource(source);const sourceId=await sourceRecord(source,f);if(f.status!==200)throw new Error(`HTTP ${f.status}`);let stats={seen:0,inserted:0,rejected:0};if(source.key==='programmes')stats=await syncProgrammes(f.html,source.url);else if(source.type==='courseware_faculty'||source.type==='courseware_degs')stats=await syncCourseware(f.html,source.url,source.title);else if(source.key==='policies')stats=await syncPolicyIndex(f.html,source.url);await db.from('sync_runs').update({status:'completed',records_seen:stats.seen,records_inserted:stats.inserted,records_rejected:stats.rejected,details:{source_id:sourceId,http_status:f.status,parser:PARSER_VERSION,fetch_ms:f.ms,content_hash:f.hash},completed_at:new Date().toISOString()}).eq('id',runId);return {key,source:source.url,...stats};}catch(e){await db.from('sync_runs').update({status:'failed',details:{error:e.message},error_count:1,completed_at:new Date().toISOString()}).eq('id',runId);throw e}}
module.exports={SOURCES,run};
