module.exports={
  authority:{
    1:'official_noun',
    2:'official_courseware',
    3:'official_noun_news',
    4:'verified_secondary_or_student',
    5:'external'
  },
  officialAllowlist:[
    'https://nou.edu.ng/',
    'https://dea.nou.edu.ng/',
    'https://dqa.nou.edu.ng/',
    'https://spgs.nou.edu.ng/'
  ],
  sources:[
    {key:'home',url:'https://nou.edu.ng/',tier:1,type:'institutional'},
    {key:'programmes',url:'https://nou.edu.ng/programmes/',tier:1,type:'programme_catalogue'},
    {key:'ecourseware',url:'https://nou.edu.ng/e-courseware/',tier:2,type:'courseware_index'},
    {key:'calendar',url:'https://nou.edu.ng/calendar/',tier:1,type:'academic_calendar'},
    {key:'pop_2026_1',url:'https://nou.edu.ng/wp-content/uploads/2026/04/2026_1-POP-EXAM-FINAL-TIMETABLE.pdf',tier:1,type:'exam_timetable'},
    {key:'dea_exam_notice',url:'https://dea.nou.edu.ng/examination_time_table_suggestion',tier:1,type:'exam_notice'},
    {key:'policies',url:'https://dqa.nou.edu.ng/policies/',tier:1,type:'policy_repository'}
  ],
  verification:{
    official_claim_requires:[1,2,3],
    secondary_claim_must_be_labelled:true,
    stale_after_days:30,
    current_timetable_requires_final_or_verified:true,
    conflicting_sources:'hold_and_surface_conflict',
    unknown:'do_not_present_as_fact'
  }
};