const crypto=require('crypto');const {db}=require('../lib/knowledge');const SECRET=process.env.WEBHOOK_SECRET;
const SOURCES={programmes:'https://nou.edu.ng/programmes/',digital_programmes:'https://digital.nou.edu.ng/programmes',policies:'https://dqa.nou.edu.ng/policies/',ecourseware:'https://nou.edu.ng/e-courseware/',calendar:'https://nou.edu.ng/calendar/'};
const OFFICIAL=/^https:\/\/(?:www\.)?(?:nou\.edu\.ng|dqa\.nou\.edu\.ng|dea\.nou\.edu\.ng)\//i;
function strip(s){return String(s||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim()}
function cells(html){return [...String(html).matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(m=>[...m[1].matchAll(/<(?:td|th)[^>]*>([\s\S]*?)<\/(?:td|th)>/gi)].map(x=>strip(x[1]))).filter(r=>r.length)}
function hash(t){return crypto.createHash('sha256').update(t).digest('hex')}
async function source(url,type,title){const r=await fetch(url,{headers:{'user-agent':'NOUN-Student-Bot-Knowledge-Sync/1.1'}});if(!r.ok)throw new Error(`${url} -> ${r.status}`);const text=await r.text();const content_hash=hash(text);const {data:existing}=await db.from('knowledge_sources').select('id').eq('source_url',url).maybeSingle();const payload={source_url:url,source_type:type,authority_tier:OFFICIAL.test(url)?1:4,title,publisher:OFFICIAL.test(url)?'National Open University of Nigeria':'Secondary source',retrieved_at:new Date().toISOString(),content_hash,status:'active'};if(existing)await db.from('knowledge_sources').update(payload).eq('id',existing.id);else await db.from('knowledge_sources').insert(payload);return text}
async function syncProgrammes(){const text=await source(SOURCES.programmes,'programme_catalogue','NOUN Programmes');let count=0;for(const r of cells(text)){if(r.length<3||/s\/no|faculty/i.test(r[0]))continue;const faculty=r.length>=4?r[1]:r[0],department=r.length>=4?r[2]:r[1],programme=r.length>=4?r[3]:r[2];if(!faculty||!department||!programme)continue;const f=await db.from('academic_faculties').upsert({name:faculty,source_url:SOURCES.programmes,source_tier:1,verified_at:new Date().toISOString()},{onConflict:'name'}).select('id').single();if(f.error)continue;const d=await db.from('academic_departments').upsert({faculty_id:f.data.id,name:department,source_url:SOURCES.programmes,source_tier:1,verified_at:new Date().toISOString()},{onConflict:'faculty_id,name'}).select('id').single();if(d.error)continue;const lower=programme.toLowerCase();const award=/mphil|phd/.test(lower)?'doctoral':/msc|m\.a|m\.ed|masters|mpa/.test(lower)?'masters':/pgd/.test(lower)?'pgd':/cert/.test(lower)?'certificate':'undergraduate';await db.from('programmes').upsert({department_id:d.data.id,title:programme,award_type:award,programme_level:award,source_url:SOURCES.programmes,source_tier:1,verification_status:'verified',verified_at:new Date().toISOString()},{onConflict:'title,department_id'});count++}return count}
async function syncPolicies(){const text=await source(SOURCES.policies,'policy_catalogue','NOUN Directorate of Quality Assurance Policies');let count=0;for(const r of cells(text)){if(r.length<2)continue;const code=r.find(x=>/NQSA\//i.test(x));const title=r.find(x=>x!==code&&x.length>10);if(!title)continue;const url=`${SOURCES.policies}#${encodeURIComponent(title.toLowerCase().replace(/[^a-z0-9]+/g,'-'))}`;await db.from('noun_policies').upsert({policy_code:code||null,title,source_url:url,policy_area:code?.split('/')[2]||null,authority_tier:1,retrieved_at:new Date().toISOString(),status:'active',summary:'Official NOUN policy listing. Details must be verified against the current policy document.'},{onConflict:'source_url'});count++}return count}
async function syncSources(){for(const [k,url] of Object.entries(SOURCES)){if(k==='programmes'||k==='policies')continue;try{await source(url,k,`NOUN ${k}`)}catch(e){console.error('source',k,e.message)}}}
module.exports=async(req,res)=>{if(req.method!=='POST')return res.status(405).json({error:'POST only'});if(SECRET&&req.headers['x-webhook-secret']!==SECRET)return res.status(401).json({error:'Unauthorized'});try{const action=req.body?.action||'all';const result={};if(action==='all'||action==='programmes')result.programmes=await syncProgrammes();if(action==='all'||action==='policies')result.policies=await syncPolicies();if(action==='all'||action==='sources')await syncSources();return res.status(200).json({ok:true,result,source_authority:'Official NOUN sources are Tier 1. Secondary sources are allowed only as explicitly labelled supplementary evidence and cannot silently override conflicting official claims.'})}catch(e){console.error(e);return res.status(500).json({error:'Knowledge sync failed'})}};
